version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./migration:/docker-entrypoint-initdb.d:ro
      - PGDATA:/var/lib/postgresql/data/
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  PGDATA: